### ISSUE TITLE
Error during carthage update

### ISSUE THREAD

**Issue by ronzohan** [braintree/braintree-ios-visa-checkout#2]
When running carthage update, i see this error message 

`objc[56507]: NSPathStore2 object 0x7f9fad609270 overreleased while already deallocating; break on objc_overrelease_during_dealloc_error to debug`

and it seems that when running my project with visa checkout dependency on my device i get this error

`/Carthage/Build/iOS/BraintreeVisaCheckout.framework/BraintreeVisaCheckout' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.`

Any resolution on this issue?

P.S.
I tried enabling the bitcode on the BraintreeVisaCheckout project and it seems to work. I'm not really sure if i'm on the right track on my solution.

**Comment by demerino** [comment]
@ronzohan Thanks for the feedback. We're looking into this issue and will update after investigating. In the meantime, let us know if you have any other insights.

**Comment by demerino** [comment]
`2.0.1` is released which should fix this issue.
